### ISSUE TITLE
Explanation about configuration on README.md

### ISSUE THREAD

**Issue by Jagni** [hukusuke1007/flamingo#1]
The example shown in readme is not clear about how rootReference is going to be created.
```Dart
import 'package:flamingo/flamingo.dart';

void main() {
  Flamingo.configure(rootName: 'version', version: 1);
  ...
}
```

My suggestion is to add this snippet or a text describing that rootName will be a collection and version a document:
```Dart
instance.rootReference =
        instance.firestore.collection('${rootName != null ? rootName : 'version'}')
            .document('${version != null ? version.toString() : '1'}');
```

Also, would it be possible to not have this structure and just use Firestore's default "/" root?

**Comment by hukusuke1007** [comment]
Thank you for comments.
I'm considering about your proposal.

**Comment by hukusuke1007** [comment]
@Jagni  Hello. 

I updated initialize spec.

```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flamingo/flamingo.dart';

void main() {
  final firestore = Firestore.instance;
  final root = firestore.collection('version').document('1');
  Flamingo.configure(firestore: firestore, storage: FirebaseStorage.instance, root: root);
  ...
}
```

Please check latest version.
[https://pub.dev/packages/flamingo/](https://pub.dev/packages/flamingo/)

Best regards.

**Comment by hukusuke1007** [comment]
close.
