### ISSUE TITLE
How to get items in a streamBuilder in realtime

### ISSUE THREAD

**Issue by tnaffh** [hukusuke1007/flamingo#11]
Hi,

Can you please show how to get items in a streambuilder and be able to update changes in realtime?

here is an example of this without using flamingo:

```dart
StreamBuilder(
          stream: db.collection('chats').orderBy('updated_at').snapshots(),
          builder: (context, snapshot) {
             //....
             // snapshots changes loaded in realtime
          },
)
```

Kindly help.

**Comment by hukusuke1007** [comment]
Can be used CollectionPagingListener.
This is a sample code.
https://github.com/hukusuke1007/flamingo/blob/master/flamingo/example/lib/collection_paging_listener_stream_builder_page.dart

**Comment by tnaffh** [comment]
Perfect. Close
