### ISSUE TITLE
Document.onCompleted() is called twice when documentAccessor.save()

### ISSUE THREAD

**Issue by hajimetakase** [hukusuke1007/flamingo#29]
I think Document.onCompleted() is called twice for each documents.

https://github.com/hukusuke1007/flamingo/blob/7437db4dd66157499d65013230032d6cba7f08a6/flamingo/lib/src/batch.dart#L126
https://github.com/hukusuke1007/flamingo/blob/7437db4dd66157499d65013230032d6cba7f08a6/flamingo/lib/src/document_accessor.dart#L37

Perhaps it should be called once for each documents after batch.commit() is completed?

**Comment by hajimetakase** [comment]
I don't use this function heavily and it could be the specification.

**Comment by hukusuke1007** [comment]
Thank you for reporting. This is bug. I will fix it.
