### ISSUE TITLE
How can I set collection name for model

### ISSUE THREAD

**Issue by vladaman** [hukusuke1007/flamingo#35]
We'd like to customize the collection name which model class uses. For example we use file name `user_model.dart` with `UserModel class` inside. We'd like the collection to be named `users`.

It would be handy to specify collection name using class annotation.

**Comment by vladaman** [comment]
So far I have found this solution to our requirement:

```dart
class UserModel extends Document<UserModel> {
  @override
  String get collectionPath => "users";
}
```

**Comment by hukusuke1007** [comment]
@vladaman Can be set model name.

```
class UserModel extends Document<UserModel> {
  @override
  String get modelName => 'users';
}
```
