### ISSUE TITLE
The data type of List being changed to null during update

### ISSUE THREAD

**Issue by huma11farheen** [hukusuke1007/flamingo#5]
Description:
The updated version allows me to deleted all the images from a list but changes the dataType to null
due to which further query to add to list cannot be done.
The dataType getting changed to null instead of array when all elements of a list are deleted 

code snippets : 

//in flamingo (UserDocument)
`writeStorageList(data, "subProfileImages", subProfileImages);`

//To fetch user Document
`final document = await DocumentAccessor()
        .load<UserDocument>(social.UserDocument(id: userId));`

Steps to reproduce:

when updating  `document.subProfileImages = []`

In Firebase:
when  images are present:
<img width="433" alt="Screenshot 2020-03-31 at 19 45 22" src="https://user-images.githubusercontent.com/56956749/78018099-3e86f580-7388-11ea-8946-ed0420e9e13e.png">

when the entire list is deleted(updated):
<img width="579" alt="Screenshot 2020-03-31 at 19 47 26" src="https://user-images.githubusercontent.com/56956749/78018304-99b8e800-7388-11ea-922b-c3a4987353cb.png">

subProfileImages becomes null due to which no further query can be made.
@hukusuke1007

**Comment by hukusuke1007** [comment]
@huma11farheen Thank you for reporting. OK, I'll modify it.

**Comment by hukusuke1007** [comment]
@huma11farheen Sorry. Please try to call 'writeStorageListNotNull'.

```
writeStorageListNotNull(data, "subProfileImages", subProfileImages);
```

Probably, If use writeStorageListNotNull, it remove a storage field in firestore.
Is it your expect's result?

**Comment by huma11farheen** [comment]
@hukusuke1007 
`writeStorageListNotNull(data, "subProfileImages", subProfileImages);`
i tried this but this deletes the entire `subProfileImages` entity  from firebase

**Comment by hukusuke1007** [comment]
@huma11farheen OK, I will modify.

**Comment by huma11farheen** [comment]
@hukusuke1007 
Thank you very much 🙏

**Comment by hukusuke1007** [comment]
@huma11farheen I updated. Please check latest version.

**Comment by huma11farheen** [comment]
@hukusuke1007 Thank you for updating, i will check 👍

**Comment by huma11farheen** [comment]
@hukusuke1007 Thank you very much, closing the issue
